config/routes.rb
Rails.application.routes.draw do

  resources "urls", only: [:new, :create, :show], param: :token
  resources "decode_urls", only: [:new, :create]

  root to: redirect(path: "/urls/new")

  get ":token" => "urls#show", as: :shortened

end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessor :short_url

  TOKEN_LENGTH = 7
  TOKEN_ALPHABET = %w{ 2 3 4 6 7 9 A C E F G H J K M N P Q R T X Y Z }

  validates :token, presence: true, uniqueness: true
  validates :long_url, presence: true, url: true

  before_validation :set_token, on: :create

  def to_param
    token
  end

  def self.with_token(token)
    where(token: token).first
  end

  private

  def set_token
    self.token = make_unique_token
  end

  def make_unique_token
    loop do
      token = build_token_value
      return token if token_is_unique?(token)
    end
  end

  def token_is_unique?(token)
    self.class.where(token: token).count == 0
  end

  def build_token_value
    (0...TOKEN_LENGTH).map { TOKEN_ALPHABET.to_a[rand(TOKEN_ALPHABET.size)] }.join
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  unless Rails.application.config.consider_all_requests_local
    rescue_from Exception, with: :render_error
    rescue_from ActiveRecord::RecordNotFound, with: :render_not_found
    rescue_from ActionController::RoutingError, with: :render_not_found
    rescue_from ActionController::UnknownController, with: :render_not_found
    rescue_from AbstractController::ActionNotFound, with: :render_not_found
  end

  private

  def render_error(exception)
    @error = exception
    respond_to do |format|
      format.html { render template: "errors/error_500", status: 500 }
      format.all { render nothing: true, status: 500 }
    end
  end

  def render_not_found(exception)
    @not_found_path = request.url
    @error_message = exception ? exception.message : nil
    respond_to do |format|
      format.html { render template: "errors/error_404", status: 404 }
      format.all { render nothing: true, status: 404 }
    end
  end
end

app/controllers/decode_urls_controller.rb
class DecodeUrlsController < ApplicationController

  def new
  end

  def create
    load_url
    redirection_to_url
  end

  private

  def load_url
    @url ||= url_scope.with_token(token_from_url)
  end

  def url_scope
    Url.all
  end

  def permitted_params
    params.require(:url).permit(:short_url)
  end

  def token_from_url
    permitted_params[:short_url].split("/").last
  end

  def redirection_to_url
    if !@url.present?
      flash[:error] = t("errors.alert.not_able_to_decode")
      redirect_to action: :new
    else
      flash[:notice] = "Success!"
      redirect_to url_path(@url.token, redirect: "no")
    end
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def show
    load_url
    redirect_to @url.long_url unless params[:redirect] == "no"
  end

  def new
    build_url
  end

  def create
    build_url(permitted_params)
    save_url or render action: "new", status: :unprocessable_entity
  end

  private

  def load_url
    @url ||= url_scope.with_token(params[:token])
    raise ActiveRecord::RecordNotFound unless @url
  end

  def build_url(url_params = nil)
    @url ||= url_scope.build
    @url.attributes = url_params if url_params
  end

  def save_url
    if @url.save
      flash[:notice] = "Success!"
      redirect_to action: :show, token: @url.token, redirect: "no"
    end
  end

  def permitted_params
    params.require(:url).permit(:long_url)
  end

  def url_scope
    Url.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"><%= t("nav.toggle") %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t("app.title"), root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render "navigation_links" %>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to t("nav.links.shorten"), new_url_path %></li>
<li><%= link_to t("nav.links.decode"), new_decode_url_path %></li>

app/views/decode_urls/new.html.erb
<%= bootstrap_form_for :url, url: decode_urls_path, inline_errors: false do |f| %>
    <%= f.text_field :short_url, class: "input-lg", placeholder: true %>
    <%= f.submit "Decode url", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : t("app.description") %>">
    <title><%= content_for?(:title) ? yield(:title) : t("app.title") %></title>

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "navigation" %>
    <main role="main">
      <%= render "messages" %>
      <%= yield %>
    </main>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/urls/new.html.erb
<%= bootstrap_form_for @url, inline_errors: false do |f| %>
    <%= f.alert_message t("errors.alert", count: @url.errors.count, model: "URL") %>
    <%= f.text_field :long_url, class: "input-lg", placeholder: true %>
    <%= f.submit class: "btn btn-primary btn-lg" %>
<% end %>

app/views/urls/show.html.erb
<div class="jumbotron">
  <h2><%= t("result.heading.short_url") %></h2>
  <p>
    <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
    <%= shortened_url(@url) %>
  </p>
  <p><em><%= t("result.heading.long_url") %></em></p>
  <p>
    <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
    <%= @url.long_url %>
  </p>
  <p>
    <%= link_to shortened_url(@url), class: "btn btn-primary btn-lg", role: "button", target: "_blank" do %>
        <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
        <%= t("result.button.visit_url") %>
    <% end %>
    <%= link_to new_url_path, class: "btn btn-default btn-lg", rule: "button" do %>
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <%= t("result.button.restart") %>
    <% end %>

    <%= link_to new_decode_url_path, class: "btn btn-default btn-lg", rule: "button" do %>
        <span class="glyphicon glyphicon-barcode" aria-hidden="true"></span>
        <%= t("result.button.decode_another") %>
    <% end %>
  </p>
</div>